#----- Device: 2432S028 WIC -----

#####Substitutions#####
substitutions:
  name: esphome-web-7682a8
  friendly_name: ESPHome 2432S028 7682a8 WIC
###############

#####Custom#####
packages: 
  - !include ./2432S028_entrance.yaml

display:
  - id: !extend hw_main_display
    rotation: 0 #玄関デバイスと異なり、Type-Cコネクタを左側に位置させるため180度回転させた。

touchscreen:
  - id: !extend hw_main_touch #タッチも同様に液晶と同じく180度回転
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: true
