#####Substitutions#####
substitutions:
  name: esphome-web-7682a8
  friendly_name: ESPHome 2432S028 7682a8 WIC
###############

#####Basic#####
esphome:
  name: ${name}
  friendly_name: ${friendly_name}

#####Custom#####
<<: !include ./2432s028_entrance.yaml

display:
  rotation: 0

touchscreen:
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: true