esphome:
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev

# Enable logging
logger:
# Enable Home Assistant API
api:
# Allow Over-The-Air updates
ota:
web_server:
    port: 80
