#####Substitutions#####
substitutions:
  name: esphome-web-2432s028
  friendly_name: ESPHome 2432S028 
###############

#####Basic#####
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

###タッチスクリーンとディスプレイのSPIピン設定
spi:
  - id: hw_tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: hw_touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

###裏面LEDとLEDバックライト
light:
  - id: ha_backlight
    platform: monochromatic
    output: hw_backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_OFF
  - platform: rgb
    name: RGB
    id: hw_led
    red: hw_led_red
    green: hw_led_green
    blue: hw_led_blue
    restore_mode: ALWAYS_OFF

sensor:
  - platform: adc
    id: hw_brightness_adc
    pin: GPIO34
    name: Brightness
    update_interval: 60s

###各GPIOの提議
output:
  - id: hw_backlight_pwm
    platform: ledc
    pin: GPIO21
  - platform: ledc
    pin: GPIO4
    id: hw_led_red
    inverted: true
  - platform: ledc
    pin: GPIO16
    id: hw_led_green
    inverted: true
  - platform: ledc
    pin: GPIO17
    id: hw_led_blue
    inverted: true

###Displays
display:
  - platform: ili9xxx
    id: hw_main_display
    model: ILI9341
    update_interval: 50ms
    color_palette: 8BIT
    spi_id: hw_tft
    color_order: rgb
    invert_colors: false
    cs_pin:
      number: 15
      ignore_strapping_warning: true
    dc_pin:
      number:  2
      ignore_strapping_warning: true
    dimensions:
      height: 240
      width: 320

###Touch Screens
touchscreen:
  - platform: xpt2046
    id: hw_main_touch
    spi_id: hw_touch
    cs_pin: GPIO33
    interrupt_pin: GPIO36
    update_interval: 50ms
    threshold: 600
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: true
    on_touch:
      lambda: |-
        id(ha_backlight).turn_on();
        auto call = id(ha_backlight).turn_off();
        call.set_delay(5 * 60 * 1000); // 5分後にOFF
        call.perform();
