esphome:
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
# Enable Home Assistant API
api:
# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

web_server:
    port: 80

###タッチスクリーンとディスプレイのSPIピン設定
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin:
      number: 12
      ignore_strapping_warning: true
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

###裏面LEDとLEDバックライト
light:
  - id: backlight
    platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    restore_mode: ALWAYS_ON
  - platform: rgb
    name: RGB
    id: led
    red: led_red
    green: led_green
    blue: led_blue
    restore_mode: ALWAYS_OFF

sensor:
  - platform: adc
    id: brightness_adc
    pin: 34
    name: Brightness
    update_interval: 15s

###各GPIOの提議
output:
  - id: backlight_pwm
    platform: ledc
    pin: GPIO21
  - platform: ledc
    pin: GPIO4
    id: led_red
    inverted: true
  - platform: ledc
    pin: GPIO16
    id: led_green
    inverted: true
  - platform: ledc
    pin: GPIO17
    id: led_blue
    inverted: true
